- hosts: localhost
  gather_facts: False

  tasks:
    - name: Import VPC Var
      include_vars: Variables/vpc_setup

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout
      
    - debug: 
          var: vpcout

    - name: Create subnet 1
        amazon.aws.ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          cidr: "{{PublicSub1cidr}}"
          region: "{{region}}"
          az: "{{zone1}}"
          state: "{{state}}"
          map_public: yes
      tags:
        Name: PubSub1 
      register: pubsub1_out