- hosts: localhost
  gather_facts: False

  tasks:
    - name: Import VPC Var
      include_vars: Variables/vpc_setup

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenansy: default
      register: vpcout
      