- hosts: localhost
  gather_facts: False

  tasks:
    - name: Import VPC Var
      include_vars: Variables/vpc_setup

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout
      
    - debug: 
          var: vpcout

    - name: Create subnet 1 in zone 1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PublicSub1cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PubSub1 
      register: pubsub1_out

    - name: Create subnet 2 in zone 2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PublicSub2cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PubSub2 
      register: pubsub2_out

    - name: Create subnet 3 in zone 3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PublicSub3cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PubSub3 
      register: pubsub1_out

    - name: Create subnet 4 in zone 1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub1cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PrivSub1 
      register: privsub1_out

    - name: Create subnet 5 in zone 2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub2cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PrivSub2 
      register: privsub2_out

    - name: Create subnet 6 in zone 3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub3cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: true
        tags:
          Name: PrivSub3 
      register: privsub3_out

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          Tag1: IGW
      register: igw_out

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Public
      subnets:
        - "{{ pubsub1_out.subnet.id }}"
        - "{{ pubsub2_out.subnet.id }}"
        - "{{ pubsub3_out.subnet_id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw_out.gateway_id }}"
        - dest: ::/0
          gateway_id: "{{ igw_out.gateway_id }}"
      register: publicRT_out