- hosts: localhost
  gather_facts: False

  tasks:
    - name: Import VPC Var
      include_vars: Variables/vpc_setup

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc-name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_spport: yes
        dns_hostnames: yes
        tenansy: default
        state: "{{state}}"
      connections: local
      register: vpcout
      